-- ═══════════════════════════════════════════════════════════════════
-- InternOri — ESQUEMA COMPLETO EN UN SOLO PASO (proyecto DEV nuevo)
-- Supabase → SQL Editor → pegar TODO → Run (≈5 segundos)
--
-- ⚠️ BORRA todas las tablas de inventario y las recrea vacías.
-- Solo usar en proyecto de DESARROLLO, nunca en producción con datos reales.
-- ═══════════════════════════════════════════════════════════════════

begin;

-- ── Limpieza (orden por dependencias FK) ───────────────────────────
drop table if exists public.producto_terminado_produccion_consumo cascade;
drop table if exists public.producto_terminado_produccion cascade;
drop table if exists public.producto_terminado_venta cascade;
drop table if exists public.packaging_componente_ingreso cascade;
drop table if exists public.packaging_requisito cascade;
drop table if exists public.packaging_componente cascade;
drop table if exists public.cafe_tostado cascade;
drop table if exists public.cafe_verde_formatos_venta cascade;
drop table if exists public.cafe_verde cascade;
drop table if exists public.health_check cascade;

-- ── Utilidades ─────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── health_check ───────────────────────────────────────────────────
create table public.health_check (
  id bigint generated by default as identity primary key,
  message text not null default 'InternOri conectado a Postgres',
  created_at timestamptz not null default now()
);

alter table public.health_check enable row level security;

drop policy if exists "health_check_select_anon" on public.health_check;
create policy "health_check_select_anon"
  on public.health_check for select to anon using (true);

insert into public.health_check (message)
values ('InternOri conectado a Postgres');

-- ── café verde ─────────────────────────────────────────────────────
create table public.cafe_verde (
  id uuid primary key default gen_random_uuid(),
  codigo text not null,
  varietal text not null,
  origen text not null,
  productor text not null,
  proceso text not null,
  fecha_ingreso date not null,
  importador text not null,
  lote text not null,
  kg_iniciales_gr numeric(14, 2) not null check (kg_iniciales_gr > 0),
  kg_usados_gr numeric(14, 2) not null default 0 check (kg_usados_gr >= 0),
  kg_actuales_gr numeric(14, 2) generated always as (kg_iniciales_gr - kg_usados_gr) stored,
  costo_total_ars numeric(14, 2) check (costo_total_ars is null or costo_total_ars >= 0),
  costo_total_usd numeric(14, 2) check (costo_total_usd is null or costo_total_usd >= 0),
  detalle text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cafe_verde_kg_usados_lte_iniciales check (kg_usados_gr <= kg_iniciales_gr)
);

create unique index cafe_verde_codigo_key on public.cafe_verde (codigo);
create unique index cafe_verde_lote_active_key on public.cafe_verde (lote) where deleted_at is null;
create index cafe_verde_deleted_at_idx on public.cafe_verde (deleted_at) where deleted_at is null;

drop trigger if exists cafe_verde_updated_at on public.cafe_verde;
create trigger cafe_verde_updated_at
  before update on public.cafe_verde
  for each row execute function public.set_updated_at();

alter table public.cafe_verde enable row level security;

drop policy if exists "cafe_verde_select_anon" on public.cafe_verde;
create policy "cafe_verde_select_anon" on public.cafe_verde for select to anon using (true);
drop policy if exists "cafe_verde_insert_anon" on public.cafe_verde;
create policy "cafe_verde_insert_anon" on public.cafe_verde for insert to anon with check (true);
drop policy if exists "cafe_verde_update_anon" on public.cafe_verde;
create policy "cafe_verde_update_anon" on public.cafe_verde for update to anon using (true) with check (true);
drop policy if exists "cafe_verde_delete_anon" on public.cafe_verde;
create policy "cafe_verde_delete_anon" on public.cafe_verde for delete to anon using (true);

-- ── formatos de venta (por lote) ───────────────────────────────────
create table public.cafe_verde_formatos_venta (
  id uuid primary key default gen_random_uuid(),
  cafe_verde_id uuid not null references public.cafe_verde (id) on delete cascade,
  formato_venta text not null,
  kg_tostado_por_unidad_gr numeric(14, 2),
  receta_bloqueada boolean not null default false,
  unidades_producidas numeric(14, 2) not null default 0 check (unidades_producidas >= 0),
  precio_venta_ars numeric(14, 2) check (precio_venta_ars is null or precio_venta_ars >= 0),
  precio_venta_usd numeric(14, 2) check (precio_venta_usd is null or precio_venta_usd >= 0),
  constraint cafe_verde_formatos_venta_formato_check
    check (formato_venta in ('50g', '100g', '125g', '150g', '200g', '250g', '500g', '1kg')),
  constraint cafe_verde_formatos_venta_unique unique (cafe_verde_id, formato_venta)
);

create index cafe_verde_formatos_venta_cafe_verde_id_idx
  on public.cafe_verde_formatos_venta (cafe_verde_id);

alter table public.cafe_verde_formatos_venta enable row level security;

drop policy if exists "cafe_verde_formatos_select_anon" on public.cafe_verde_formatos_venta;
create policy "cafe_verde_formatos_select_anon"
  on public.cafe_verde_formatos_venta for select to anon using (true);
drop policy if exists "cafe_verde_formatos_insert_anon" on public.cafe_verde_formatos_venta;
create policy "cafe_verde_formatos_insert_anon"
  on public.cafe_verde_formatos_venta for insert to anon with check (true);
drop policy if exists "cafe_verde_formatos_update_anon" on public.cafe_verde_formatos_venta;
create policy "cafe_verde_formatos_update_anon"
  on public.cafe_verde_formatos_venta for update to anon using (true) with check (true);
drop policy if exists "cafe_verde_formatos_delete_anon" on public.cafe_verde_formatos_venta;
create policy "cafe_verde_formatos_delete_anon"
  on public.cafe_verde_formatos_venta for delete to anon using (true);

-- ── café tostado ───────────────────────────────────────────────────
create table public.cafe_tostado (
  id uuid primary key default gen_random_uuid(),
  codigo text not null,
  cafe_verde_codigo text not null references public.cafe_verde (codigo),
  fecha_tueste date not null,
  perfil text not null,
  kg_verde_tostado_gr numeric(14, 2) not null check (kg_verde_tostado_gr > 0),
  kg_despues_tostar_gr numeric(14, 2) not null check (kg_despues_tostar_gr > 0),
  merma_gr numeric(14, 2) generated always as (kg_verde_tostado_gr - kg_despues_tostar_gr) stored,
  kg_vendidos_gr numeric(14, 2) not null default 0 check (kg_vendidos_gr >= 0),
  kg_existentes_gr numeric(14, 2) generated always as (kg_despues_tostar_gr - kg_vendidos_gr) stored,
  detalle text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cafe_tostado_merma_no_negativa check (kg_despues_tostar_gr <= kg_verde_tostado_gr),
  constraint cafe_tostado_kg_vendidos_lte_despues check (kg_vendidos_gr <= kg_despues_tostar_gr)
);

create unique index cafe_tostado_codigo_active_key on public.cafe_tostado (codigo) where deleted_at is null;
create index cafe_tostado_deleted_at_idx on public.cafe_tostado (deleted_at) where deleted_at is null;

drop trigger if exists cafe_tostado_updated_at on public.cafe_tostado;
create trigger cafe_tostado_updated_at
  before update on public.cafe_tostado
  for each row execute function public.set_updated_at();

alter table public.cafe_tostado enable row level security;

drop policy if exists "cafe_tostado_select_anon" on public.cafe_tostado;
create policy "cafe_tostado_select_anon" on public.cafe_tostado for select to anon using (true);
drop policy if exists "cafe_tostado_insert_anon" on public.cafe_tostado;
create policy "cafe_tostado_insert_anon" on public.cafe_tostado for insert to anon with check (true);
drop policy if exists "cafe_tostado_update_anon" on public.cafe_tostado;
create policy "cafe_tostado_update_anon" on public.cafe_tostado for update to anon using (true) with check (true);
drop policy if exists "cafe_tostado_delete_anon" on public.cafe_tostado;
create policy "cafe_tostado_delete_anon" on public.cafe_tostado for delete to anon using (true);

-- ── catálogo packaging ─────────────────────────────────────────────
create table public.packaging_componente (
  id uuid primary key default gen_random_uuid(),
  componente text not null,
  tipo text not null,
  cantidad numeric(14, 2) not null default 0 check (cantidad >= 0),
  precio_compra_ars numeric(14, 2) check (precio_compra_ars is null or precio_compra_ars >= 0),
  precio_compra_usd numeric(14, 2) check (precio_compra_usd is null or precio_compra_usd >= 0),
  detalle text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint packaging_componente_componente_check
    check (componente in ('sticker', 'bolsa_cafe', 'bolsa_sosten', 'caja', 'sobre', 'tarjeta')),
  constraint packaging_componente_unique unique (componente, tipo)
);

create index packaging_componente_componente_tipo_idx
  on public.packaging_componente (componente, tipo);

drop trigger if exists packaging_componente_updated_at on public.packaging_componente;
create trigger packaging_componente_updated_at
  before update on public.packaging_componente
  for each row execute function public.set_updated_at();

alter table public.packaging_componente enable row level security;

drop policy if exists "packaging_componente_select_anon" on public.packaging_componente;
create policy "packaging_componente_select_anon"
  on public.packaging_componente for select to anon using (true);
drop policy if exists "packaging_componente_insert_anon" on public.packaging_componente;
create policy "packaging_componente_insert_anon"
  on public.packaging_componente for insert to anon with check (true);
drop policy if exists "packaging_componente_update_anon" on public.packaging_componente;
create policy "packaging_componente_update_anon"
  on public.packaging_componente for update to anon using (true) with check (true);
drop policy if exists "packaging_componente_delete_anon" on public.packaging_componente;
create policy "packaging_componente_delete_anon"
  on public.packaging_componente for delete to anon using (true);

-- ── requisitos packaging por formato ───────────────────────────────
create table public.packaging_requisito (
  id uuid primary key default gen_random_uuid(),
  cafe_verde_formato_id uuid not null
    references public.cafe_verde_formatos_venta (id) on delete cascade,
  packaging_componente_id uuid not null
    references public.packaging_componente (id) on delete restrict,
  componente text not null,
  tipo text not null,
  cantidad numeric(14, 2) not null default 0 check (cantidad >= 0),
  cantidad_por_unidad numeric(14, 2) not null default 0 check (cantidad_por_unidad >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint packaging_requisito_componente_check
    check (componente in ('sticker', 'bolsa_cafe', 'bolsa_sosten', 'caja', 'sobre', 'tarjeta')),
  constraint packaging_requisito_formato_componente_unique
    unique (cafe_verde_formato_id, packaging_componente_id)
);

create index packaging_requisito_formato_id_idx on public.packaging_requisito (cafe_verde_formato_id);
create index packaging_requisito_componente_id_idx on public.packaging_requisito (packaging_componente_id);

drop trigger if exists packaging_requisito_updated_at on public.packaging_requisito;
create trigger packaging_requisito_updated_at
  before update on public.packaging_requisito
  for each row execute function public.set_updated_at();

alter table public.packaging_requisito enable row level security;

drop policy if exists "packaging_requisito_select_anon" on public.packaging_requisito;
create policy "packaging_requisito_select_anon"
  on public.packaging_requisito for select to anon using (true);
drop policy if exists "packaging_requisito_insert_anon" on public.packaging_requisito;
create policy "packaging_requisito_insert_anon"
  on public.packaging_requisito for insert to anon with check (true);
drop policy if exists "packaging_requisito_update_anon" on public.packaging_requisito;
create policy "packaging_requisito_update_anon"
  on public.packaging_requisito for update to anon using (true) with check (true);
drop policy if exists "packaging_requisito_delete_anon" on public.packaging_requisito;
create policy "packaging_requisito_delete_anon"
  on public.packaging_requisito for delete to anon using (true);

-- ── ingresos packaging ─────────────────────────────────────────────
create table public.packaging_componente_ingreso (
  id uuid primary key default gen_random_uuid(),
  packaging_componente_id uuid not null
    references public.packaging_componente (id) on delete cascade,
  cantidad numeric(14, 2) not null check (cantidad > 0),
  stock_anterior numeric(14, 2) not null check (stock_anterior >= 0),
  stock_nuevo numeric(14, 2) not null check (stock_nuevo >= 0),
  precio_compra_ars numeric(14, 2) check (precio_compra_ars is null or precio_compra_ars >= 0),
  precio_compra_usd numeric(14, 2) check (precio_compra_usd is null or precio_compra_usd >= 0),
  origen text not null default 'manual'
    check (origen in ('manual', 'alta', 'ajuste')),
  notas text,
  created_at timestamptz not null default now()
);

create index packaging_componente_ingreso_componente_idx
  on public.packaging_componente_ingreso (packaging_componente_id, created_at desc);
create index packaging_componente_ingreso_created_idx
  on public.packaging_componente_ingreso (created_at desc);

alter table public.packaging_componente_ingreso enable row level security;

drop policy if exists "packaging_componente_ingreso_select_anon" on public.packaging_componente_ingreso;
create policy "packaging_componente_ingreso_select_anon"
  on public.packaging_componente_ingreso for select to anon using (true);
drop policy if exists "packaging_componente_ingreso_insert_anon" on public.packaging_componente_ingreso;
create policy "packaging_componente_ingreso_insert_anon"
  on public.packaging_componente_ingreso for insert to anon with check (true);
drop policy if exists "packaging_componente_ingreso_delete_anon" on public.packaging_componente_ingreso;
create policy "packaging_componente_ingreso_delete_anon"
  on public.packaging_componente_ingreso for delete to anon using (true);

-- ── producción producto terminado ──────────────────────────────────
create table public.producto_terminado_produccion (
  id uuid primary key default gen_random_uuid(),
  cafe_verde_formato_id uuid not null
    references public.cafe_verde_formatos_venta (id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  unidades_totales integer not null check (unidades_totales >= 0),
  kg_tostado_usado_gr numeric(14, 2) not null check (kg_tostado_usado_gr >= 0),
  precio_venta_ars numeric(14, 2) check (precio_venta_ars is null or precio_venta_ars >= 0),
  precio_venta_usd numeric(14, 2) check (precio_venta_usd is null or precio_venta_usd >= 0),
  origen text not null default 'individual'
    check (origen in ('individual', 'lote')),
  detalle text,
  created_at timestamptz not null default now()
);

create index producto_terminado_produccion_created_idx
  on public.producto_terminado_produccion (created_at desc);
create index producto_terminado_produccion_formato_idx
  on public.producto_terminado_produccion (cafe_verde_formato_id, created_at desc);

alter table public.producto_terminado_produccion enable row level security;

drop policy if exists "producto_terminado_produccion_select_anon" on public.producto_terminado_produccion;
create policy "producto_terminado_produccion_select_anon"
  on public.producto_terminado_produccion for select to anon using (true);
drop policy if exists "producto_terminado_produccion_insert_anon" on public.producto_terminado_produccion;
create policy "producto_terminado_produccion_insert_anon"
  on public.producto_terminado_produccion for insert to anon with check (true);
drop policy if exists "producto_terminado_produccion_delete_anon" on public.producto_terminado_produccion;
create policy "producto_terminado_produccion_delete_anon"
  on public.producto_terminado_produccion for delete to anon using (true);

-- ── consumo por producción ─────────────────────────────────────────
create table public.producto_terminado_produccion_consumo (
  id uuid primary key default gen_random_uuid(),
  produccion_id uuid not null
    references public.producto_terminado_produccion (id) on delete cascade,
  es_tostado boolean not null default false,
  componente text,
  tipo text not null,
  cantidad_por_unidad numeric(14, 2),
  cantidad_usada numeric(14, 2) not null check (cantidad_usada >= 0),
  unidad text not null default 'ud' check (unidad in ('g', 'ud'))
);

create index producto_terminado_produccion_consumo_produccion_idx
  on public.producto_terminado_produccion_consumo (produccion_id);

alter table public.producto_terminado_produccion_consumo enable row level security;

drop policy if exists "producto_terminado_produccion_consumo_select_anon" on public.producto_terminado_produccion_consumo;
create policy "producto_terminado_produccion_consumo_select_anon"
  on public.producto_terminado_produccion_consumo for select to anon using (true);
drop policy if exists "producto_terminado_produccion_consumo_insert_anon" on public.producto_terminado_produccion_consumo;
create policy "producto_terminado_produccion_consumo_insert_anon"
  on public.producto_terminado_produccion_consumo for insert to anon with check (true);
drop policy if exists "producto_terminado_produccion_consumo_delete_anon" on public.producto_terminado_produccion_consumo;
create policy "producto_terminado_produccion_consumo_delete_anon"
  on public.producto_terminado_produccion_consumo for delete to anon using (true);

-- ── ventas producto terminado ────────────────────────────────────────
create table public.producto_terminado_venta (
  id uuid primary key default gen_random_uuid(),
  cafe_verde_formato_id uuid not null
    references public.cafe_verde_formatos_venta (id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  unidades_restantes integer not null check (unidades_restantes >= 0),
  precio_venta numeric(14, 2) check (precio_venta is null or precio_venta >= 0),
  tipo_cliente text not null
    check (tipo_cliente in ('cliente_final', 'mayorista', 'oficina')),
  fecha date not null default (current_date),
  detalle text,
  created_at timestamptz not null default now()
);

create index producto_terminado_venta_fecha_idx
  on public.producto_terminado_venta (fecha desc, created_at desc);
create index producto_terminado_venta_formato_idx
  on public.producto_terminado_venta (cafe_verde_formato_id, fecha desc);

alter table public.producto_terminado_venta enable row level security;

drop policy if exists "producto_terminado_venta_select_anon" on public.producto_terminado_venta;
create policy "producto_terminado_venta_select_anon"
  on public.producto_terminado_venta for select to anon using (true);
drop policy if exists "producto_terminado_venta_insert_anon" on public.producto_terminado_venta;
create policy "producto_terminado_venta_insert_anon"
  on public.producto_terminado_venta for insert to anon with check (true);
drop policy if exists "producto_terminado_venta_delete_anon" on public.producto_terminado_venta;
create policy "producto_terminado_venta_delete_anon"
  on public.producto_terminado_venta for delete to anon using (true);

commit;

-- Verificación rápida
select tablename
from pg_tables
where schemaname = 'public'
  and tablename in (
    'health_check', 'cafe_verde', 'cafe_verde_formatos_venta', 'cafe_tostado',
    'packaging_componente', 'packaging_requisito', 'packaging_componente_ingreso',
    'producto_terminado_produccion', 'producto_terminado_produccion_consumo',
    'producto_terminado_venta'
  )
order by tablename;
