-- Ejecutar en Supabase: SQL Editor → New query → pegar y Run

create table if not exists public.health_check (
  id bigint generated by default as identity primary key,
  message text not null default 'InternOri conectado a Postgres',
  created_at timestamptz not null default now()
);

alter table public.health_check enable row level security;

create policy "health_check_select_anon"
  on public.health_check
  for select
  to anon
  using (true);

insert into public.health_check (message)
select 'InternOri conectado a Postgres'
where not exists (select 1 from public.health_check);
